// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VacinaBtgApi.Data;

#nullable disable

namespace VacinaBtgApi.Migrations
{
    [DbContext(typeof(VacinaDbContext))]
    [Migration("20250826042249_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("VacinaBtgApi.Models.Dose", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PessoaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VacinaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("numero")
                        .HasColumnType("INTEGER");

                    b.Property<int>("tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.HasIndex("VacinaId");

                    b.ToTable("Doses");
                });

            modelBuilder.Entity("VacinaBtgApi.Models.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("idade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("sexo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("VacinaBtgApi.Models.Vacina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("numeroDose")
                        .HasColumnType("INTEGER");

                    b.Property<int>("numeroReforco")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("semLimiteDose")
                        .HasColumnType("INTEGER");

                    b.Property<int>("tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Vacinas");
                });

            modelBuilder.Entity("VacinaBtgApi.Models.Dose", b =>
                {
                    b.HasOne("VacinaBtgApi.Models.Pessoa", "Pessoa")
                        .WithMany("Doses")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VacinaBtgApi.Models.Vacina", "Vacina")
                        .WithMany("Doses")
                        .HasForeignKey("VacinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");

                    b.Navigation("Vacina");
                });

            modelBuilder.Entity("VacinaBtgApi.Models.Pessoa", b =>
                {
                    b.Navigation("Doses");
                });

            modelBuilder.Entity("VacinaBtgApi.Models.Vacina", b =>
                {
                    b.Navigation("Doses");
                });
#pragma warning restore 612, 618
        }
    }
}
